nelmio_api_doc:
    documentation:
        info:
            title: Api stock
            description: Servicio para el control de stock de productos!
            version: 1.0.0
        paths:
            /categoria/all:
                get:
                    description: Devuelve todas las categorias de productos.
                    tags:
                        - Categorias
                    responses:
                        200:
                            description: OK
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: { type: integer, example: 1 }
                                            nombre: { type: string, example: Bebidas }
            /categoria/add:
                post:
                    description: Crea una categoria inexistente.
                    tags:
                        - Categorias
                    requestBody:
                        content:
                            aplication/json:
                                schema:
                                    type: object
                                    properties:
                                        nombre: {type: string, example: bebidas}
            /categoria/{id}:
                get:
                    tags:
                        - Categorias
                    responses:
                        200:
                            description: Devuelve información de la categoria solicitada por id
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: { type: integer, example: 1 }
                                            nombre: { type: string, example: Bebidas }
                    parameters:
                      - in: path
                        name: id
                        required: true
                        schema:
                            type: integer
                            minimum: 1
                        description: Id de la categoria
            /categoria/{id}/productos:
                get:
                    tags:
                        - Categorias
                    responses:
                        200:
                            description: Devuelve todos los productos pertenecientes a la categoria pasada por parametro
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: { type: integer, example: 1 }
                                            nombre: { type: string, example: Bebidas }
                                            productos:
                                                type: object
                                                properties:
                                                    id: { type: integer, example: 1 }
                                                    nombre: { type: string, example: Picadillo de carne 90g }
                    parameters:
                      - in: path
                        name: id
                        required: true
                        schema:
                            type: integer
                            minimum: 1
                        description: Id de la categoria de las cuales se quiere obtener los productos
            /producto/add:
                post:
                    description: Crea un producto y lo asocia a una categoria
                    tags: 
                        - Productos
                    requestBody:
                        content:
                            aplication/json:
                                schema:
                                    type: object
                                    properties:
                                        nombre: {type: string, example: Picadillo de carne Carrefour 90 g}
                                        codigoColor: {type: string, example: 005BAA}
                                        precio: {type: float, example: 50}
                                        categoria: {type: integer, example: 2}
            /producto/all:
                get:
                    description: Devuelve la lista de productos
                    tags:
                        - Productos
                    responses:
                        200:
                            description: OK
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: {type: integer, example: 1}
                                            nombre: {type: string, example: Picadillo de carne Carrefour 90 g}
                                            codigoColor: {type: string, example: 005BAA}
                                            precio: {type: float, example: 50}
                                            categoria: 
                                                type: object
                                                properties:
                                                    id: {type: integer, example: 1}
                                                    nombre: {type: string, example: bebidas}
                                            foto: {type: string, example: null}
            /producto/{id}:
                get:
                    tags:
                        - Productos
                    responses:
                        200:
                            description: OK
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: {type: integer, example: 1}
                                            nombre: {type: string, example: Picadillo de carne Carrefour 90 g}
                                            codigoColor: {type: string, example: 005BAA}
                                            precio: {type: float, example: 50}
                                            categoria: 
                                                type: object
                                                properties:
                                                    id: {type: integer, example: 1}
                                                    nombre: {type: string, example: bebidas}
                                            foto: {type: string, example: null}
                    parameters:
                      - in: path
                        name: id
                        required: true
                        schema:
                            type: integer
                            minimum: 1
                        description: Id del producto que se quiere obtener
            /deposito/add:
                post:
                    description: Crea un deposito inexistente.
                    tags:
                        - Depositos
                    requestBody:
                        content:
                            aplication/json:
                                schema:
                                    type: object
                                    properties:
                                        nombre: {type: string, example: B1}
                                        direccion: {type: string, example: Calle falsa 123}
            /deposito/all:
                get:
                    tags:
                        - Depositos
                    responses:
                        200:
                            description: Devuelve todos los depositos existentes
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: {type: integer, example: 1}
                                            nombre: {type: string, example: B1}
                                            direccion: {type: string, example: Calle falsa 123}
            /deposito/{id}:
                get:
                    tags:
                        - Depositos
                    responses:
                        200:
                            description: Devuelve un deposito por id
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: {type: integer, example: 1}
                                            nombre: {type: string, example: B1}
                                            direccion: {type: string, example: Calle falsa 123}
                    parameters:
                      - in: path
                        name: id
                        required: true
                        schema:
                            type: integer
                            minimum: 1
                        description: Id del deposito que se quiere obtener
            /deposito/{id}/productos:
                get:
                    tags:
                        - Depositos
                    responses:
                        200:
                            description: Devuelve los productos existentes en el deposito pasado por parametro
                            content:
                                aplication/json:
                                    schema:
                                        type: object
                                        properties:
                                            id: {type: integer, example: 1}
                                            nombre: {type: string, example: B1}
                                            direccion: {type: string, example: Calle falsa 123}
                                            productos:
                                                type: object
                                                properties:
                                                    id: {type: integer, example: 1}
                                                    nombre: {type: string, example: Picadillo de carne Carrefour 90 g}
                                                    codigoColor: {type: string, example: 005BAA}
                                                    precio: {type: float, example: 50}
                                                    categoria: 
                                                        type: object
                                                        properties:
                                                            id: {type: integer, example: 1}
                                                            nombre: {type: string, example: bebidas}
                                                    cantidad: {type: integer, example: 50}

        tags:
            - name: Categorias
            - name: Productos
            - name: Depositos

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
