
imports:
  - { resource: nelmio_api_doc/deposito.yaml }
  - { resource: nelmio_api_doc/producto.yaml }
  - { resource: nelmio_api_doc/categoria.yaml }

nelmio_api_doc:
    documentation:
        info:
            title: API-STOCK
            description: Api Rest Full para gestionar el stock de productos en sus respectivos almacenes.
            version: 1.0.0
        components:
            schemas:
                RecursoEliminado:
                    type: object
                    properties:
                        title: {type: string, example: "Recurso no eliminado"}

                Error500:
                    type: object
                    properties:
                        errors:
                            type: array
                            items:
                                type: object
                                properties:
                                    status: 
                                        type: integer
                                        example: 500
                                    title: 
                                        type: string
                                        example: Internal server error
                                    detail: 
                                        type: string
                                        example: IzAgL3Zhci93d3cvaHRtbC92ZW5kb3Ivc3ltZm9ueS9odHRwLWtlcm5....
                Error409:
                    type: object
                    properties:
                        errors:
                            type: array
                            items:
                                type: object
                                properties:
                                    status: 
                                        type: integer
                                        example: 409
                                    title: 
                                        type: string
                                        example: Conflicto de recurso
                                    detail: 
                                        type: string
                                        example: Ya un producto con dicho codigo.
                
                Error404:
                    type: object
                    properties:
                        errors:
                            type: array
                            items:
                                type: object
                                properties:
                                    status: { type: integer, example: 404 }
                                    title: { type: string, example: Recurso no encontrado}
                                    detail: { type: string, example: La categoria no se encuentra.}

                Error400:
                    type: object
                    properties:
                        codigo: {type: integer, example: 4554}
                        nombre: {type: integer, example: ADAPTADORES-WIFI}

        paths:
            /api/1.0/stock/deposito/incrementar:
                post:
                    description: Crea un deposito inexistente.
                    tags:
                        - StockDeposito
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        codigoProducto: {type: integer, example: 3322}
                                        codigoDeposito: {type: integer, example: 4554}
                                        cantidad: {type: integer, example: 10}
                    responses:
                        200:
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            success: { type: boolean, example: true }
                                            message: { type: string, example: OK }
                                            data: { type: integer, example: 200 }
                        404:
                            description: Not Found
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Error404'
                        500:
                            description: Internal server error
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Error500'
            /api/1.0/stock/deposito/decrementar:
                put:
                    description: Decrementa la cantidad de unidades disponibles de un producto en un depósito.
                    tags:
                        - StockDeposito
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        codigoProducto: {type: integer, example: 3322}
                                        codigoDeposito: {type: integer, example: 4554}
                                        cantidad: {type: integer, example: 10} 
                    responses:
                        200:
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            success: { type: boolean, example: true }
                                            message: { type: string, example: OK }
                                            data: { type: integer, example: 200 }
                        404:
                            description: Not Found
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Error404'
                        500:
                            description: Internal server error
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Error500'
        tags:
            - name: Categorias
              description: Categorias a las cuales puede pertenecer un producto.
            - name: Productos
              description: Productos disponibles en los diferentes depositos.
            - name: Depositos
              description: Ubicaciones donde se alojan los diferentes productos.
            - name: StockDeposito
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

