nelmio_api_doc:
    documentation:
        info:
            title: App stock
            description: Servicio para el control de stock de productos!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
